### ISSUE TITLE
Is it possible to test with another stock than IBM ?

### ISSUE THREAD

**Issue by LuWahl** [jinglescode/time-series-forecasting-pytorch#16]
If I try Amazon (AMZ) in config, I get the following error message:

Traceback (most recent call last):
  File "c:\daten\Python\boerse_deep_learning\boerse_deep_learning.py", line 72, in <module>
    data_date, data_close_price, num_data_points, display_date_range = download_data(config)
  File "c:\daten\Python\boerse_deep_learning\boerse_deep_learning.py", line 54, in download_data
    data, meta_data = ts.get_daily_adjusted(config["alpha_vantage"]["symbol"], \
    call_response, data_key, meta_data_key = func(
  File "C:\daten\programme\python\python310\lib\site-packages\alpha_vantage\alphavantage.py", line 160, in _call_wrapper
    return self._handle_api_call(url), data_key, meta_data_key
  File "C:\daten\programme\python\python310\lib\site-packages\alpha_vantage\alphavantage.py", line 359, in _handle_api_call
    raise ValueError(json_response["Error Message"])
ValueError: Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_DAILY_ADJUSTED.

Regards 
Lu

**Comment by ryansilk** [comment]
Hi LuWahl - hope you're well. 

You're getting this error as the ticker symbol for Amazon is 'AMZN', whereas you've asked for 'AMZ'. 

The mistyping of the ticker symbol is resulting in the error from the API call. 

By changing AMZ to AMZN, the API call will work correctly.

**Comment by LuWahl** [comment]
Hi ryansilk

sorry was very stupid from me. In Germany Amazon is listed as AMZ.de. I just removed  .de 
Thank you AMZN and Microsoft are working.
